// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleDashboardAPI.Data;

#nullable disable

namespace VehicleDashboardAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241209235447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleDashboardAPI.Models.DashboardData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryPercentage")
                        .HasColumnType("int");

                    b.Property<int>("BatteryTemperature")
                        .HasColumnType("int");

                    b.Property<bool>("ChargingState")
                        .HasColumnType("bit");

                    b.Property<string>("GearRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotorRPM")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DashboardData");
                });
#pragma warning restore 612, 618
        }
    }
}
